// Self-hosts the four Google Fonts the site uses (latin subset only).
// Run once; re-run only to change families or weights.
// Keeps the site free of third-party requests so the CSP can stay strict.
import { writeFile, mkdir, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const SPEC = 'https://fonts.googleapis.com/css2?family=Bungee&family=Archivo:wght@400..800&family=Newsreader:opsz,wght@6..72,400..600&family=Yellowtail&display=swap';
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await (await fetch(SPEC, { headers: { 'User-Agent': UA } })).text();
await mkdir('assets/fonts', { recursive: true });

// Keep only the latin block of each @font-face group.
const blocks = css.split(/(?=\/\*)/).filter(b => /@font-face/.test(b));
const keep = blocks.filter(b => /^\/\*\s*latin\s*\*\//.test(b.trim()));

const seen = new Map();   // content hash -> filename, so one variable font is stored once
let outCss = '/* Self-hosted subset of Bungee, Archivo, Newsreader and Yellowtail.\n' +
             '   Generated by tools/fetch-fonts.mjs. All four are free for commercial\n' +
             '   use (Bungee / Archivo / Newsreader: SIL OFL 1.1, Yellowtail: Apache 2.0).\n' +
             '   See LICENSES.md. */\n';
let n = 0;
for (const b of keep) {
  const url = b.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  if (!url) continue;
  const fam = b.match(/font-family: '([^']+)'/)[1].toLowerCase().replace(/\s+/g, '-');
  const wght = (b.match(/font-weight: ([^;]+);/)?.[1] || '400').replace(/\s+/g, '');
  const name = `${fam}-${wght.replace(/\s/g, '')}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const hash = createHash('sha256').update(buf).digest('hex');
  let file = seen.get(hash);
  if (!file) { file = name; seen.set(hash, file); await writeFile(`assets/fonts/${file}`, buf); }
  outCss += b.replace(/\/\*[^*]*\*\/\s*/, '')
             .replace(/url\([^)]+\)/, `url(../fonts/${file})`)
             .replace(/\n\s*unicode-range:[^;]+;/, '') + '\n';
  n++;
  console.log(`${name} -> ${file}  ${(buf.length / 1024).toFixed(1)} KB`);
}
await writeFile('assets/css/fonts.css', outCss);
console.log(`faces=${n}`);
